### ISSUE TITLE
About the definition of launchOptions ?

### ISSUE THREAD

**Issue by StringKe** [tinovyatkin/nest-puppeteer#463]
https://github.com/tinovyatkin/nest-puppeteer/blob/master/src/interfaces/puppeteer-options.interface.ts#L10

https://github.com/puppeteer/puppeteer/blob/main/src/node/LaunchOptions.ts#L126

```
export declare function launch(options?: LaunchOptions & BrowserLaunchArgumentOptions & BrowserConnectOptions & {
    product?: Product;
    extraPrefsFirefox?: Record<string, unknown>;
}): Promise<Browser>;
```

![image](https://user-images.githubusercontent.com/31089228/123753716-bb3ab380-d8ec-11eb-8905-757f2dfdd4f1.png)

The latest version of `puppeteer` already supports the definition of typescript, but does `nest-puppeteer` definition of typescript need to be updated?

**Comment by beneccli** [comment]
Yes it seems there's an issue with the options, on one side `launch` method accepts `LaunchOptions`,  `BrowserLaunchArgumentOptions` and `BrowserConnectOptions` but `forRoot` only accepts `LaunchOptions`.

This is troublesome since if we want to disable the headless mode or add args, we should be able to use `BrowserLaunchArgumentOptions` which contains these attributes and not only `LaunchOptions`.

A workaround working on my side is to type cast the options with `any`:
`PuppeteerModule.forRoot(<any>{ pipe: true, headless: false })`
